# Assignment 1: Shubhayan Bhattacharya, IIT Madras (GroupB, ML)

In [1]:
import numpy as np
import pandas as pd

### Question 1: Convert tuple to list, set, Dictionary 


In [2]:
tuple_cars = (('USA','Ford'), ('Japan','Honda'), ('Italy','Alfa Romeo'), ('India', 'Maruti'))
print (tuple_cars)
type (tuple_cars)



(('USA', 'Ford'), ('Japan', 'Honda'), ('Italy', 'Alfa Romeo'), ('India', 'Maruti'))


tuple

In [3]:
list1=list (tuple_cars)
print (list1)
type (list1)

[('USA', 'Ford'), ('Japan', 'Honda'), ('Italy', 'Alfa Romeo'), ('India', 'Maruti')]


list

In [4]:
set1=set (tuple_cars)
print(set1)
type(set1)

{('Italy', 'Alfa Romeo'), ('India', 'Maruti'), ('Japan', 'Honda'), ('USA', 'Ford')}


set

In [5]:
dict1=dict (tuple_cars)
print (dict1)
type (dict1)

{'USA': 'Ford', 'Japan': 'Honda', 'Italy': 'Alfa Romeo', 'India': 'Maruti'}


dict

### Question 2: Convert list to tuple, set, Dictionary 


In [18]:
list_cars =[('USA', 'Ford'),('Japan', 'Honda'),('Italy', 'Alfa Romeo'),('India', 'Maruti')]
print(list_cars)
type(list_cars)

[('USA', 'Ford'), ('Japan', 'Honda'), ('Italy', 'Alfa Romeo'), ('India', 'Maruti')]


list

In [10]:
tuple1= tuple (list_cars)
print (tuple1)
type (tuple1)

(('USA', 'Ford'), ('Japan', 'Honda'), ('Italy', 'Alfa Romeo'), ('India', 'Maruti'))


tuple

In [11]:
set2=set (list_cars)
print(set2)
type(set2)

{('Italy', 'Alfa Romeo'), ('India', 'Maruti'), ('Japan', 'Honda'), ('USA', 'Ford')}


set

In [12]:
dict1=dict (list_cars)
print (dict1)
type(dict1)

{'USA': 'Ford', 'Japan': 'Honda', 'Italy': 'Alfa Romeo', 'India': 'Maruti'}


dict

### Question 3: Convert set to list, tuple, Dictionary 

In [13]:
print (set2)
type (set2)


{('Italy', 'Alfa Romeo'), ('India', 'Maruti'), ('Japan', 'Honda'), ('USA', 'Ford')}


set

In [14]:
list3=list (set2)
print (list3)
type (list3)

[('Italy', 'Alfa Romeo'), ('India', 'Maruti'), ('Japan', 'Honda'), ('USA', 'Ford')]


list

In [15]:
tuple2= tuple (set2)
print (tuple2)
type (tuple2)

(('Italy', 'Alfa Romeo'), ('India', 'Maruti'), ('Japan', 'Honda'), ('USA', 'Ford'))


tuple

In [16]:
dict2=dict(set2)
print (dict2)
type (dict2)

{'Italy': 'Alfa Romeo', 'India': 'Maruti', 'Japan': 'Honda', 'USA': 'Ford'}


dict

### Question 4: Convert Dictionary to list, set, tuple

In [17]:
print (dict2)
type (dict2)

{'Italy': 'Alfa Romeo', 'India': 'Maruti', 'Japan': 'Honda', 'USA': 'Ford'}


dict

In [18]:
list4 = [(k, v) for k, v in dict2.items()]
print (list4)
type (list4)

[('Italy', 'Alfa Romeo'), ('India', 'Maruti'), ('Japan', 'Honda'), ('USA', 'Ford')]


list

In [19]:
set3= set (dict2)
print (set3)
type (set3)

{'Japan', 'Italy', 'USA', 'India'}


set

In [20]:
import collections
list5 = collections.namedtuple('List', 'name value') 
print (list5)
type (list5)

<class '__main__.List'>


type

### Question 5: Create a list and perform pop, append, update, remove, delete, add element and sort operation

In [21]:
list_fruits= ['apple', 'banana', 'guava', 'watermelon', 'orange']
type (list_fruits)

list

In [22]:
print (list_fruits)

['apple', 'banana', 'guava', 'watermelon', 'orange']


In [23]:
z= list_fruits.pop()
print (z)

orange


In [24]:
list_fruits.append('apple')
print(list_fruits)

['apple', 'banana', 'guava', 'watermelon', 'apple']


In [114]:
list_fruits.remove('apple')
print(list_fruits)

['banana', 'guava', 'watermelon']


In [4]:
# sort option
listnumbers=[14, 56, 78, 93, 43]
listnumbers.sort()
listnumbers

[14, 43, 56, 78, 93]

### Question 6: Create a tuple and perform pop, append, update, remove, delete, add element and sort operation

In [22]:
# tuple is immutable and most of the above operations cannot be performed
list_new=[1,3, 5, 87, 45, 22]
tuple_new=tuple(list_new)
type(tuple_new)

tuple

In [26]:
sorted(tuple_new)

[1, 3, 5, 22, 45, 87]

### Question 7: Create a set and perform pop, append, update, remove, delete, add element and sort operation

In [6]:
set_numbers = {13, 34, 56, 78, 98, 108, 212}
type(set_numbers)

set

In [7]:
#perform pop
pop1=set_numbers.pop()
set_numbers

{13, 56, 78, 98, 108, 212}

In [10]:
# performing add
set_numbers.add(68)
set_numbers

{108, 13, 212, 56, 68, '68', 78, 98}

In [15]:
# performing remove
set_numbers.remove('68')
set_numbers

{13, 56, 78, 98, 108, 212}

### Question 9: How to make a copy of list, tuple and dictionary 

In [29]:
# for list
old_list_primenumbers = [2, 3, 5, 7, 11]
new_list = old_list_primenumbers.copy()

# add element to list
new_list.append('a')

print('New List:', new_list )
print('Old List:', old_list_primenumbers )

New List: [2, 3, 5, 7, 11, 'a']
Old List: [2, 3, 5, 7, 11]


In [34]:
# for tuple
tuple_cars = (('USA','Ford'), ('Japan','Honda'), ('Italy','Alfa Romeo'), ('India', 'Maruti'))
newt = tuple_cars
# tuple is immutable

In [36]:
#for dict
dict1 = {"fruit": "orange", "car": "Ford"}
dict2 = dict1.copy()
dict2

{'fruit': 'orange', 'car': 'Ford'}

### Question 10: Write a function which accept input from keyboard and check if student grade should be First division, second division or Fail 

In [38]:
print("Enter 'x' for exit.");
print("Enter marks obtained in 3 subjects: ");
mark1 = input();
if mark1 == 'x':
    exit();
else:
    sub1 = int(mark1);
    sub2 = int(input());
    sub3 = int(input());
    sum = sub1 + sub2 + sub3;
    average = sum/3;
    if(average>=80 and average<=100):
    	print("Your division is 1");
    elif(average>=61 and average<=79):
    	print("Your division is 2");
    elif(average>=41 and average<=60):
    	print("Your division is 3");
    elif(average>=0 and average<=39):
    	print("Your division is fail");

Enter 'x' for exit.
Enter marks obtained in 3 subjects: 
98
58
87
Your division is 1


 ### Question 11-13: 
- teamA = {'India', 'Australia','Pakistan', 'England'}
- teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}
- use add, clear, copy, difference, differenc_update(), discard, intersection, intersection_update, 
- remove, symmetric_difference,  union, update 


In [42]:
teamA = {'India', 'Australia','Pakistan', 'England'}
teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}
# using add
teamA.add('Netherlands')
teamA

{'Australia', 'England', 'India', 'Netherlands', 'Pakistan'}

In [44]:
# using clear 
teamA.clear()
teamA

set()

In [45]:
# using copy
teamA = {'India', 'Australia','Pakistan', 'England'}
teamC=teamA.copy()
teamC

{'Australia', 'England', 'India', 'Pakistan'}

In [46]:
# using difference
z=teamA.difference(teamB)
z

{'Australia', 'England', 'Pakistan'}

In [49]:
# using differenc_update()
y=teamA.difference_update(teamB)
print(y)

None


In [52]:
# using discard
teamA.discard('Australia')
teamA.discard('Pakistan')
teamA

{'England'}

In [55]:
# using intersection
teamA = {'India', 'Australia','Pakistan', 'England'}
teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}
c = teamA.intersection (teamB)
print(c)

{'India'}


In [57]:
# using intersection_update
d=teamA.intersection_update(teamB)
print(d)

None


In [60]:
# using remove function
teamA.remove("India")
teamA

set()

In [61]:
# symmetric difference 
teamA = {'India', 'Australia','Pakistan', 'England'}
teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}
teamA.symmetric_difference(teamB)

{'Australia',
 'Bangladesh',
 'England',
 'New Zealand',
 'Pakistan',
 'West Indies'}

In [62]:
# using union
teamA = {'India', 'Australia','Pakistan', 'England'}
teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}
teamA.union(teamB)

{'Australia',
 'Bangladesh',
 'England',
 'India',
 'New Zealand',
 'Pakistan',
 'West Indies'}

### Question 14:	What is list comprehension explain with 2 examples

#### List comprehensions in python is a short and concise way of creating new lists using sequences which have already been defined. 

### Example 1

In [9]:
input_list_numbers = [61, 62, 73, 54, 84, 55, 61, 74, 47] 
  
output_list = [] 
# We wish to create a list with only even numbers 
for var in input_list_numbers: 
    if var % 2 == 0: 
        output_list.append(var) 
  
print("Output List using for loop:", output_list) 

Output List using for loop: [62, 54, 84, 74]


### Example 2

In [10]:
squarenumber=[i**2 for i in range(2,10)]
print (squarenumber)

[4, 9, 16, 25, 36, 49, 64, 81]


### Question 15: What is the difference between List and tuple, explain with example

#### Major differences between list and tuple are as follows:
- List is mutable but tuple is immutable
- Syntax for list and tuple are different
- Tuples can consist of heterogeneous data structures but list consists of homogeneous data sequences

In [ ]:
listdays =['Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun']
type (listdays)


#### Mutability

In [25]:
listdays[2]='Wednesday'
print (listdays)

['Mon', 'Tues', 'Wednesday', 'Thurs', 'Fri', 'Sat', 'Sun']


In [19]:
tupledays=('Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun')
type (tupledays)

tuple

#### Immutability

In [26]:
tupledays(2)='Wednesday'

SyntaxError: can't assign to function call (<ipython-input-26-14ea1c7d1567>, line 1)

### Question 16: What is the output of

In [116]:
if 1 and 0:
    print("Sucess 1 and 0")
elif 0 and 0:
    print("Sucess 0 and 0")
elif 0 and 1 or 1:
    print("Sucess 0 and 1 or 1")
elif 0 and 0 or 1 and 1:
    print("Sucess : 0 and 0 or 1 and 1")



Sucess 0 and 1 or 1


### Question 17: What is the output of

In [117]:
list_of_lists = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
for list1 in list_of_lists: 
    for x in list1: 
        print(x)
    print(list1)


10
20
30
[10, 20, 30]
40
50
60
[40, 50, 60]
70
80
90
[70, 80, 90]


### Question 18: Print  the numpy version and the configuration

In [118]:
print(np.__version__)

1.16.5


In [119]:
print(np.show_config())

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Bisht/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Bisht/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Bisht/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/U

### Question 19: Create a vector with values ranging from 10 to 29

In [132]:
from numpy import array
w=np.arange(10,30)
v= array (w)
print(v)
type(v)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


numpy.ndarray

### Question 20: Create a 3x3 matrix with values ranging from 0 to 8 

In [135]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Question 21: Create a 10x10 array with random values and find the minimum and maximum values

In [136]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Min and Max Values:")
print(xmin, xmax)

Original Array:
[[0.00423658 0.46291104 0.9401926  0.80777509 0.95037424 0.93578901
  0.50212759 0.03213456 0.71772165 0.52380602]
 [0.45473417 0.68869643 0.11559674 0.27651296 0.24995512 0.55171653
  0.28025371 0.30183612 0.80399117 0.28024414]
 [0.48950463 0.65845958 0.8719045  0.97552375 0.06558185 0.75553982
  0.75660248 0.0290311  0.07373396 0.97468577]
 [0.0830907  0.89014726 0.19236247 0.30408378 0.29228277 0.72104334
  0.46939453 0.02412001 0.5304301  0.60566662]
 [0.1751445  0.8848475  0.8350587  0.4260589  0.07041979 0.05126772
  0.13580153 0.96028611 0.56726698 0.85812077]
 [0.07492442 0.38412704 0.13719086 0.67121662 0.79565169 0.49080063
  0.82564373 0.66831781 0.96097311 0.4761756 ]
 [0.58753416 0.03633565 0.01600496 0.12449883 0.6947049  0.05972928
  0.81131477 0.70577045 0.77638984 0.26905289]
 [0.63522514 0.40392275 0.36798368 0.72064459 0.27702549 0.18708565
  0.85987955 0.84277488 0.36911004 0.4820346 ]
 [0.10566631 0.58064282 0.97396925 0.3860952  0.54627917 0.86661

### Question 22: Create a random vector of size 30 and find the mean and median value 

In [157]:
y = np.random.random(30)
print("Original array:")
print(y)
import statistics
xmean,xmedian = statistics.mean(y),statistics.median(y)
print ("Meanvalue and Medianvalue")
print(xmean,xmedian)

Original array:
[0.73592688 0.2170691  0.45418003 0.79447199 0.79866278 0.43048484
 0.01571716 0.48651231 0.75037716 0.19044042 0.62538958 0.79502096
 0.33884686 0.05572676 0.51769364 0.35177491 0.85056823 0.07012216
 0.59221299 0.85323157 0.36920413 0.08253434 0.74231823 0.64401426
 0.30221983 0.32559089 0.15500882 0.13604979 0.2060225  0.71665049]
Meanvalue and Medianvalue
0.45346812044371276 0.4423324354314189


### Question 23: Define an array and find the max value and index of max value

In [163]:
s=np.array([14,17,87,105,64,89,12])
Maxvalue=np.amax(s)
print(Maxvalue)

105


In [166]:
result = np.where(s == np.amax(s)) 
print('Returned tuple of arrays :', result)
print('List of Indices of maximum element :', result[0])

Returned tuple of arrays : (array([3], dtype=int64),)
List of Indices of maximum element : [3]


### Question 24: How to find the memory size of any array

In [170]:
n = np.zeros((1440,6))
print("%d bytes" % (n.size * n.itemsize))

69120 bytes


### Question 25: Create a 3x3 identity matrix 

In [179]:
a = np.identity(3) 
print("\nMatrix a : \n", a) 


Matrix a : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
